### ISSUE TITLE
TCPServer operator is crashing during client disconnection

### ISSUE THREAD

**Issue by alexelkun** [IBMStreams/streamsx.tcp#15]
Hi,

During testing of streamsx.tcp_v1.1.1 drop, the TCPServer operator was crashed many times.
In all cases, it happened when output queue of TCPServer operator was not empty and client application was stopped.

The major different between previous tests was that I changed configuration of the TCPServer operator by defining "shutdown" value for new  disableDuplexConnection parameter 

In all cases, the following exception was reported into Streams log files:

22 Jul 2015 11:48:33.293 [6426] ERROR #splapptrc,J[7],P[97],TCPServerInstance_3,spl_operator M[PEImpl.h:onMessage:508]  - CDISR5030E: An exception occurred during the execution of the TCPServerInstance_3 operator. The exception is: Transport endpoint is not connected

I don't know how to attach log files to the issue. So, I sent the log files and testing application code by email

Thanks,

Alex.

**Comment by chanskw** [comment]
Thanks Alex.  We are looking at this.

When you say client application was stopped, was the client application stop abruptly?  
Or was it gracefully shutdown?  Not sure it makes a difference, but I want to understand the scenario.  How was the client stopped?

Was the client stopped because there were too many tuples buffered on the server? and that the server attempts to shutdown the connection?

How many client did you have running at the same time?

**Comment by leongor** [comment]
Fixed - closing the issue.
