### ISSUE TITLE
Separate Transmit/Recieve blockSize 

### ISSUE THREAD

**Issue by siegenth** [IBMStreams/streamsx.tcp#25]
I'm using the TCPServer operator bidirectionally, in raw mode.  I receive a huge amount of data and need to send a 12 byte acknowledgment message, once. This requires that I set the blockSize to 12 in order to transmit the buffer. In rawmode the message is send when the blockSize is filled - 12 in 
this case. As a consequence my receive buffers are only 12, when I'm transmitted 120,000 bytes I get 10,000 messages of 12 bytes. 

An alternative to having a transmitBlockSize / receiveBlockSize, sending a 0 length buffer to mean the buffer should be flushed. Then I could set the receive blockSize to 12,000.

thanks

**Comment by leongor** [comment]
Actually a blockSize parameter is not used for sending because the data size is known. For efficiency the data also is not copied, but adopted from the  blob attribute, so there is no buffer to flush - it's just the whole blob is sent immediately.
Did you try to set a blockSize to the desired value for input data? Did it cause some problem?

**Comment by siegenth** [comment]
My apologies, it works as you described - it does transmit the buffer even it's less than the blockSize. The protocol has changed a number of times and I was misinterpreting/confused the processing. 

I'll close this. 
thanks
